#!/usr/bin/env python3
"""Stage 2g: sample candidates for a hand-verified residual label set.

This script picks *what* a human should look at. It never fills in a
`verdict` itself -- that is the one part of Stage 2g that isn't automatable
(see `.cursor/plans/iterative_gr-ol_matcher_loop_dfcdd41a.plan.md`). Every
entry it writes has `verdict: null`; a human must review each one and set
`verdict` (see the YAML header comment this script writes, or
`docs/BOOK_CATALOG.md`'s residual-label-set section) before
`tools.catalog.bibliographic_join.load_residual_labels` treats it as
ground truth.

Samples four strata from `matched_goodreads.jsonl.gz` -- the population no
other automated check in this pipeline can currently verify (the ISBN-gold
set only covers books with a harvested ISBN; the adversarial set only
covers hand-picked pairs, not real matcher output):

- `unmatched_popular` -- `match_method="unmatched"`, real GR `ratings_count`
  above `--min-ratings-count`. No OL candidate was even found for these; a
  human check says whether OL is actually missing the book or the
  title-probe missed it.
- `ambiguous_popular` -- `match_method="ambiguous"` above the same
  threshold. The matcher found candidates but declined to pick between
  them; shows the top scored candidate for reference.
- `low_margin_title_author` -- `match_method="title_author"` with the
  smallest `match_margin` -- confident enough to pick, but the closest
  calls, so the most likely to be silently wrong.
- `suspicious_duplicate` -- one entry per `goodreads_book_id` inside a
  `tools.catalog.eval_canaries.suspicious_duplicate_targets` group (multiple
  GR books sharing one OL `work_key` with metadata that doesn't obviously
  agree). Each entry asks whether *this specific* `book_id` really belongs
  at that shared `work_key`.

Re-running this script overwrites `--out` with a fresh, unverified sample --
it does not merge with a previously hand-reviewed file. Copy any verdicts
you want to keep before re-sampling, or pass a different `--out` and merge
by hand.

Usage:
    python tools/catalog/sample_matcher_residual_candidates.py \\
        --matched $BOOK_SPINES_DATA/derived/book-catalog/goodreads/matched_goodreads.jsonl.gz \\
        --ol-db $BOOK_SPINES_DATA/derived/book-catalog/full.sqlite \\
        --out tools/catalog/matcher_residual_labels.yaml
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path
from typing import Iterable

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from tools.catalog.bibliographic_join import (  # noqa: E402
    OLCandidate,
    TitleAuthorBlockIndex,
    names_compatible,
    title_core,
    title_score,
)
from tools.catalog.eval_canaries import load_matched_rows, suspicious_duplicate_targets  # noqa: E402
from tools.paths import catalog_goodreads  # noqa: E402

DEFAULT_PER_STRATUM = 40
DEFAULT_MIN_RATINGS_COUNT = 2_000

_YAML_HEADER = """\
# Stage 2g hand-verified residual label set. Generated by
# tools/catalog/sample_matcher_residual_candidates.py (candidates only --
# see that script's docstring); a human fills in `verdict` for each entry
# before tools.catalog.bibliographic_join.load_residual_labels treats it as
# ground truth. Entries with `verdict: null` are ignored -- unreviewed, not
# ground truth. See docs/BOOK_CATALOG.md's residual-label-set section for
# the full protocol.
#
# verdict values (fill in one per entry; leave others null/empty):
#   correct       -- candidate_work_key really is this Goodreads book.
#   wrong         -- candidate_work_key is NOT this book. If you know the
#                    right OL workKey, put it in corrected_work_key.
#   no_ol_match   -- this Goodreads book genuinely has no entry in Open
#                    Library at all (e.g. self-published, too obscure).
#   unsure        -- couldn't tell from title/author alone.
#
# sample_reason meanings:
#   unmatched_popular       -- no OL candidate was found at all.
#   ambiguous_popular       -- matcher found candidates, declined to pick;
#                              candidate_* is its top-scored guess only.
#   low_margin_title_author -- matcher picked candidate_work_key, but by a
#                              thin margin over the runner-up.
#   suspicious_duplicate    -- this book_id shares candidate_work_key with
#                              another Goodreads book whose title/author
#                              don't obviously match it.
"""


def _fmt_scalar(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    text = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def write_residual_labels_yaml(entries: list[dict], out_path: Path) -> None:
    """Hand-rolled YAML writer (not `yaml.safe_dump`): keeps field order
    stable and human-review-friendly (context first, verdict fields last)
    instead of alphabetized, and keeps every entry on one visual block a
    reviewer can scan without scrolling past a reformatted dump.
    """
    lines = [_YAML_HEADER, "entries:"]
    fields = (
        "goodreads_book_id",
        "sample_reason",
        "gr_title",
        "gr_author",
        "gr_ratings_count",
        "match_method",
        "candidate_work_key",
        "candidate_title",
        "candidate_author",
        "candidate_edition_count",
        "match_score",
        "match_margin",
        "verdict",
        "corrected_work_key",
        "notes",
    )
    for entry in entries:
        for i, field in enumerate(fields):
            prefix = "  - " if i == 0 else "    "
            lines.append(f"{prefix}{field}: {_fmt_scalar(entry.get(field))}")
        lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _base_entry(row: dict, sample_reason: str) -> dict:
    return {
        "goodreads_book_id": row.get("goodreads_book_id"),
        "sample_reason": sample_reason,
        "gr_title": row.get("title"),
        "gr_author": row.get("author"),
        "gr_ratings_count": row.get("ratings_count"),
        "match_method": row.get("match_method"),
        "candidate_work_key": None,
        "candidate_title": None,
        "candidate_author": None,
        "candidate_edition_count": None,
        "match_score": row.get("match_score"),
        "match_margin": row.get("match_margin"),
        "verdict": None,
        "corrected_work_key": None,
        "notes": "",
    }


def top_scored_candidate(title: str, author: str, index: TitleAuthorBlockIndex) -> OLCandidate | None:
    """Best name-compatible candidate by title_score -- the same signal
    `bibliographic_join.match_title_author` ranks by, exposed here purely
    for human review context (an ambiguous/unmatched row has no work_key
    of its own to look up)."""
    compatible = [c for c in index.candidates_for(title, author) if names_compatible(author, c.author)]
    if not compatible:
        return None
    gr_core = title_core(title)
    return max(compatible, key=lambda c: (title_score(gr_core, c.title_core), c.edition_count))


def load_ol_rows_by_work_key(conn: sqlite3.Connection, work_keys: Iterable[str]) -> dict[str, tuple[str, str, int]]:
    keys = sorted({k for k in work_keys if k})
    out: dict[str, tuple[str, str, int]] = {}
    for offset in range(0, len(keys), 400):
        chunk = keys[offset : offset + 400]
        placeholders = ",".join("?" * len(chunk))
        rows = conn.execute(
            f"SELECT workKey, title, author, editionCount FROM books WHERE workKey IN ({placeholders})", chunk
        ).fetchall()
        for work_key, title, author, edition_count in rows:
            out[work_key] = (title, author, edition_count or 0)
    return out


def sample_unmatched_or_ambiguous(
    rows: list[dict], *, method: str, min_ratings_count: int, per_stratum: int
) -> list[dict]:
    pool = [r for r in rows if r.get("match_method") == method and (r.get("ratings_count") or 0) >= min_ratings_count]
    pool.sort(key=lambda r: -(r.get("ratings_count") or 0))
    return pool[:per_stratum]


def sample_low_margin_title_author(rows: list[dict], *, per_stratum: int) -> list[dict]:
    pool = [r for r in rows if r.get("match_method") == "title_author" and r.get("match_margin") is not None]
    pool.sort(key=lambda r: r["match_margin"])
    return pool[:per_stratum]


def build_residual_candidates(
    rows: list[dict],
    conn: sqlite3.Connection,
    *,
    min_ratings_count: int = DEFAULT_MIN_RATINGS_COUNT,
    per_stratum: int = DEFAULT_PER_STRATUM,
) -> list[dict]:
    entries: list[dict] = []

    unmatched_rows = sample_unmatched_or_ambiguous(
        rows, method="unmatched", min_ratings_count=min_ratings_count, per_stratum=per_stratum
    )
    ambiguous_rows = sample_unmatched_or_ambiguous(
        rows, method="ambiguous", min_ratings_count=min_ratings_count, per_stratum=per_stratum
    )
    # Probe against every matched row's title, not just the sampled ~80 --
    # a probe restricted to the sample alone can miss real OL candidates
    # that only got pulled into the pool because some *other* GR book's
    # title happened to hit them (title_lookup_keys is title-text-derived,
    # not book-specific), silently under-representing what the real
    # match_goodreads.py run actually considered for this exact row.
    from tools.catalog.match_goodreads import load_ol_candidates_for_titles  # local: see that module's TYPE_CHECKING note

    probe_titles = [r["title"] for r in rows if r.get("title")]
    index = TitleAuthorBlockIndex(load_ol_candidates_for_titles(conn, probe_titles))

    for row in unmatched_rows:
        entry = _base_entry(row, "unmatched_popular")
        cand = top_scored_candidate(row["title"], row["author"], index)
        if cand:
            entry["candidate_work_key"] = cand.work_key
            entry["candidate_title"] = cand.title
            entry["candidate_author"] = cand.author
            entry["candidate_edition_count"] = cand.edition_count
        entries.append(entry)

    for row in ambiguous_rows:
        entry = _base_entry(row, "ambiguous_popular")
        cand = top_scored_candidate(row["title"], row["author"], index)
        if cand:
            entry["candidate_work_key"] = cand.work_key
            entry["candidate_title"] = cand.title
            entry["candidate_author"] = cand.author
            entry["candidate_edition_count"] = cand.edition_count
        entries.append(entry)

    low_margin_rows = sample_low_margin_title_author(rows, per_stratum=per_stratum)
    ol_by_key = load_ol_rows_by_work_key(conn, (r["work_key"] for r in low_margin_rows))
    for row in low_margin_rows:
        entry = _base_entry(row, "low_margin_title_author")
        entry["candidate_work_key"] = row["work_key"]
        ol_row = ol_by_key.get(row["work_key"])
        if ol_row:
            entry["candidate_title"], entry["candidate_author"], entry["candidate_edition_count"] = ol_row
        entries.append(entry)

    dup_report = suspicious_duplicate_targets(rows)
    dup_groups = dup_report["suspicious_duplicate_examples"][:per_stratum]
    by_book_id = {r.get("goodreads_book_id"): r for r in rows}
    for group in dup_groups:
        work_key = group["work_key"]
        ol_row = ol_by_key.get(work_key) or load_ol_rows_by_work_key(conn, [work_key]).get(work_key)
        for book_id in group["book_ids"]:
            gr_row = by_book_id.get(book_id)
            if gr_row is None:
                continue
            entry = _base_entry(gr_row, "suspicious_duplicate")
            entry["candidate_work_key"] = work_key
            if ol_row:
                entry["candidate_title"], entry["candidate_author"], entry["candidate_edition_count"] = ol_row
            entries.append(entry)

    return entries


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--matched", type=Path, default=None, help="Default: catalog_goodreads('matched_goodreads.jsonl.gz')"
    )
    parser.add_argument("--ol-db", type=Path, required=True)
    parser.add_argument("--min-ratings-count", type=int, default=DEFAULT_MIN_RATINGS_COUNT)
    parser.add_argument("--per-stratum", type=int, default=DEFAULT_PER_STRATUM)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent / "matcher_residual_labels.yaml",
    )
    args = parser.parse_args(argv)

    matched_path = args.matched or catalog_goodreads("matched_goodreads.jsonl.gz")
    rows = load_matched_rows(matched_path)
    print(f"[sample_matcher_residual_candidates] loaded {len(rows)} matched rows from {matched_path}")

    conn = sqlite3.connect(f"file:{args.ol_db}?mode=ro", uri=True)
    try:
        entries = build_residual_candidates(
            rows, conn, min_ratings_count=args.min_ratings_count, per_stratum=args.per_stratum
        )
    finally:
        conn.close()

    write_residual_labels_yaml(entries, args.out)
    by_reason: dict[str, int] = {}
    for e in entries:
        by_reason[e["sample_reason"]] = by_reason.get(e["sample_reason"], 0) + 1
    print(f"[sample_matcher_residual_candidates] wrote {len(entries)} candidates to {args.out}: {by_reason}")
    print("[sample_matcher_residual_candidates] every entry has verdict: null -- needs human review before use.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
