#!/usr/bin/env python3
"""Generate `book_show_api_chunked` — a copy of the harness's live `book_show_api`
profile with `policy.max_requests` overridden, so a session cap bounds each
`scrape-harness scrape` invocation instead of one run trying to walk the whole
`ids_remaining.txt` (potentially tens of thousands of items) in one Chrome
session.

Mirrors `tools/scrape_goodreads_lists.py`'s `_write_chunked_profile` /
`list_show_chunked` for the list-scrape side — see that function's docstring
for why this is a real profile file on disk rather than a `--set` override
(scrape-harness's `--set` only substitutes into `start_url`/`url_pattern`,
not `policy`).

Usage:
    python tools/catalog/write_book_show_api_chunked_profile.py
    python tools/catalog/write_book_show_api_chunked_profile.py --max-requests 200
    python tools/catalog/write_book_show_api_chunked_profile.py --delay-ms-min 1500 --delay-ms-max 4000
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

_REPO = Path(__file__).resolve().parents[2]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

BASE_PROFILE_ID = "book_show_api"
CHUNKED_PROFILE_ID = "book_show_api_chunked"
DEFAULT_HARNESS_ROOT = _REPO.parent / "scrape-harness"
DEFAULT_MAX_REQUESTS = 120


def write_chunked_profile(
    harness_root: Path,
    max_requests: int,
    delay_ms_min: int | None = None,
    delay_ms_max: int | None = None,
) -> Path:
    """Writes/overwrites `book_show_api_chunked.yaml` next to the live
    `book_show_api.yaml` in the harness's own `sites/goodreads/profiles/`
    directory, and returns the written path.

    Rewritten on every call so it always mirrors whatever `book_show_api.yaml`
    currently does (delays, required_fields, extract expressions) — never
    hand-edit the generated file. `delay_ms_min`/`delay_ms_max`, when given,
    override the base profile's delays (e.g. for a pacing benchmark trial or
    an env-var-driven live run); omit them to inherit the base as-is.
    """
    base_path = harness_root / "sites" / "goodreads" / "profiles" / f"{BASE_PROFILE_ID}.yaml"
    if not base_path.exists():
        raise FileNotFoundError(f"Expected base profile at {base_path} — is the harness site set up?")

    data = yaml.safe_load(base_path.read_text(encoding="utf-8"))
    data["id"] = CHUNKED_PROFILE_ID
    policy = dict(data.get("policy") or {})
    policy["max_requests"] = max_requests
    if delay_ms_min is not None:
        policy["delay_ms_min"] = delay_ms_min
    if delay_ms_max is not None:
        policy["delay_ms_max"] = delay_ms_max
    data["policy"] = policy

    out_path = base_path.parent / f"{CHUNKED_PROFILE_ID}.yaml"
    header = (
        "# AUTO-GENERATED by book-train/tools/catalog/write_book_show_api_chunked_profile.py.\n"
        "# Mirrors book_show_api.yaml with policy.max_requests (and optionally delay_ms_min/max)\n"
        "# overridden. Do not hand-edit — rewritten on every orchestrator run.\n"
    )
    out_path.write_text(header + yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
    return out_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--harness-root", type=Path, default=DEFAULT_HARNESS_ROOT)
    parser.add_argument(
        "--max-requests",
        type=int,
        default=DEFAULT_MAX_REQUESTS,
        help=f"Session cap per scrape-harness invocation (default: {DEFAULT_MAX_REQUESTS}).",
    )
    parser.add_argument(
        "--delay-ms-min", type=int, default=None, help="Override policy.delay_ms_min (default: inherit base profile)."
    )
    parser.add_argument(
        "--delay-ms-max", type=int, default=None, help="Override policy.delay_ms_max (default: inherit base profile)."
    )
    args = parser.parse_args(argv)

    try:
        out_path = write_chunked_profile(args.harness_root, args.max_requests, args.delay_ms_min, args.delay_ms_max)
    except FileNotFoundError as exc:
        print(f"[write_book_show_api_chunked_profile] {exc}", file=sys.stderr)
        return 1

    delay_suffix = (
        f", delay_ms={args.delay_ms_min}-{args.delay_ms_max}" if args.delay_ms_min or args.delay_ms_max else ""
    )
    print(f"[write_book_show_api_chunked_profile] wrote {out_path} (max_requests={args.max_requests}{delay_suffix})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
